# Generated by Django 6.0.3 on 2026-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0002_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='best_time_to_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
