# Generated by Django 6.0.3 on 2026-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domesinnheaven_app', '0003_contactmessage_best_time_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
